FORMAT: 1A
HOST: https://iitd7euw75.execute-api.us-east-1.amazonaws.com/services

# CoffeeShop

Coffee Shop API (CSYE)

## Products Collection [/products/getProducts]

### Get list of Products [GET]
+ Response 200 (application/json)

        {
    "items": [
        {
            "id": "63dc592c-c1b7-4c7c-b85f-7bb64a0e63c5",
            "price": 300,
            "name": "cafe",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/A_small_cup_of_coffee.JPG/251px-A_small_cup_of_coffee.JPG",
            "Created": 1573526475359
        }
        ],
    "status": 200
        }

## Create Product [/products/createProduct]
### Create a New Product [PUT]

+ Request (application/json)

        {
            "name": "cafe",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/A_small_cup_of_coffee.JPG/251px-A_small_cup_of_coffee.JPG",
            "price": 300
        }

+ Response 200 (application/json)

        {
            "id": "63dc592c-c1b7-4c7c-b85f-7bb64a0e63c5",
            "status": 200
        }
        
## Update Product [/products/updateProduct]
### Update Product [POST]

+ Request (application/json)

        {
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/A_small_cup_of_coffee.JPG/251px-A_small_cup_of_coffee.jpg",
            "price": 305,
            "id": "bb6a902d-bbcb-4c80-9db0-389fb759bf4c",
            "name": "Café"
        }

+ Response 200 (application/json)

        {
            "status": 200
        }

## Delete Product [/products/deleteProduct]
### Delete Product [DELETE]

+ Request (application/json)

        {
            "id": "bb6a902d-bbcb-4c80-9db0-389fb759bf4c",
        }

+ Response 200 (application/json)

        {
            "status": 200
        }


## Create Order [/orders/createOrder]
### Create a New Product [PUT]

+ Request (application/json)

        {
            "items": [{"id": "63dc592c-c1b7-4c7c-b85f-7bb64a0e63c5", "qty": 3}],
            "user": "Danny Chaves"
        }

+ Response 200 (application/json)

        {
            "id": "63dc592c-c1b7-4c7c-b85f-7bb64a0e63c5",
            "status": 200
        }
        
## Orders Collection [/orders/getOrders]

### Get list of Orders [GET]
+ Response 200 (application/json)

        {
    "items": [
        {
            "createdAt": 1573528877065,
            "user": "Gabriel Rodriguez",
            "id": "33f80f46-402d-4389-8de6-a333eb09d75c",
            "items": [
                {
                    "id": "63dc592c-c1b7-4c7c-b85f-7bb64a0e63c5",
                    "qty": 1
                }
            ],
            "updatedAt": 1573528877065,
            "state": "pending"
        },
        {
            "createdAt": 1573528886090,
            "user": "Danny Chaves",
            "id": "876da453-204f-40a5-b0b2-936a51a74aec",
            "items": [
                {
                    "id": "63dc592c-c1b7-4c7c-b85f-7bb64a0e63c5",
                    "qty": 3
                }
            ],
            "updatedAt": 1573529451298,
            "state": "complete"
        }  
        ],
    "status": 200
        }

## Update Order Status [/orders/updateOrder]

### Update order Status [POST]

+ Request (application/json)

        {
            "id": "876da453-204f-40a5-b0b2-936a51a74aec",
            "state": "complete"
        }


+ Response 200 (application/json)

        {
            "status": 200
        }

        